@baseURL = http://localhost:8081

### Criar Categoria
POST {{baseURL}}/categorias
Content-Type: application/json

{
    "nome": "Informática"
}

### Listar categorias
GET {{baseURL}}/categorias


### Criar produtos vinculados à categoria
POST {{baseURL}}/produtos
Content-Type: application/json

{
    "nome": "Notebook",
    "descricao": "Notebook DELL",
    "preco": 3500.0,
    "categoria": {"id": 1}

}

### Buscar produtos por categoria
GET {{baseURL}}/produtos/categoria/1

### Buscar produtos por faixa de preço
GET {{baseURL}}/produtos/faixa-preco?min=50&max=200


### Apagar produto
DELETE {{baseURL}}/produtos/9




